# Generated by Django 4.1.4 on 2022-12-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='start_date')),
                ('due_date', models.DateField(verbose_name='end_date')),
                ('fee_aud', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='fee_aud')),
                ('fee_rmb', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='fee_rmb')),
                ('payment_date', models.DateField(verbose_name='payment_date')),
                ('comments', models.CharField(max_length=1000, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('create_user', models.CharField(max_length=100)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('update_user', models.CharField(max_length=100)),
                ('is_deleted', models.IntegerField(default=0)),
            ],
        ),
    ]
