# Generated by Django 4.1.4 on 2022-12-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='fee_aud',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='fee_aud'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='fee_rmb',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='fee_rmb'),
        ),
    ]
