# Generated by Django 4.1.4 on 2022-12-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_bill_fee_aud_alter_bill_fee_rmb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
