# Generated by Django 4.1.4 on 2022-12-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(default='male', max_length=20)),
                ('create_time', models.DateTimeField(default='2022-12-19 03:23:49')),
                ('update_time', models.DateTimeField(default='2022-12-19 03:23:49')),
                ('is_deleted', models.IntegerField(default=0)),
            ],
        ),
    ]
