# Generated by Django 4.1.4 on 2022-12-19 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demomodel',
            name='create_user',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demomodel',
            name='update_user',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='demomodel',
            name='create_time',
            field=models.DateTimeField(default='2022-12-19 04:16:32'),
        ),
        migrations.AlterField(
            model_name='demomodel',
            name='update_time',
            field=models.DateTimeField(default='2022-12-19 04:16:32'),
        ),
    ]
