# Generated by Django 4.1.4 on 2022-12-25 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_demomodel_create_user_demomodel_update_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demomodel',
            name='create_time',
            field=models.DateTimeField(default='2022-12-25 01:00:11'),
        ),
        migrations.AlterField(
            model_name='demomodel',
            name='update_time',
            field=models.DateTimeField(default='2022-12-25 01:00:11'),
        ),
    ]
