# Generated by Django 4.1.4 on 2022-12-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_alter_demomodel_create_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demomodel',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='demomodel',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
